const data = {
    products: [
      {
        name: 'Divya Swasari Pravahi',
        slug: 'divya-svasari-pravahi',
        category: 'Medicine',
        image: '/images/p1.jpg', // 679px × 829px
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'Divya swasari pravahi activates the cells of the lungs. It alleviates respiratory tract and lung inflammation. Its use enhances easy expulsion of cough deposited in the lungs. It is an effective ayurvedic medicine used for the treatment of asthma.',
      },
      {
        name: 'Divya Taila (50ml)',
        slug: 'divya-taila',
        category: 'Medicine',
        image: '/images/p2.jpg',
        price: 250,
        countInStock: 20,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'Divya taila is useful for Psorasis, Skin inflammation, Sthanik Shoth(Local Inflammation) & work as Skin Nourisher.',
      },
      {
        name: 'LaxmiVilas Ras',
        slug: 'laxmi-vilas-ras',
        category: 'Cosmetics',
        image: '/images/p3.jpg',
        price: 25,
        countInStock: 15,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'Laxmivilas Ras is a traditional Ayurvedic formulation that cures a cough, cold and rhinitis. It soothes the throat and sinuses.',
      },
      {
        name: 'Divya Usirasav',
        slug: 'divya-usirasav',
        category: 'Medicine',
        image: '/images/p4.jpg',
        price: 65,
        countInStock: 5,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'Divya Usirasav is an ayurvedic product used for ahaemostatic and pitta pacifying. It is diuretic, cooling, tranquilizer and blood purifier. Divya Usirasav is a liquid ',
      },
      {
        // _id: '1',
        name: 'Delicate Facial Cleanser Kashmiri Saffron',
        slug: 'delicate-herbal',
        category: 'Cosmetics',
        image: '/images/p5.jpg', // 679px × 829px
        price: 40,
        countInStock: 0,
        brand: 'Panchtatva',
        rating: 5,
        numReviews: 20,
        description: 'Specially designed to treat sensitive, acne-prone, and oily skin, the Delicate Facial Cleanser Kashmiri Saffron & Neem, leaves the skin clarified, glowing and balanced',
      },
      {
        // _id: '1',
        name: 'Pradha Varnya Lepa',
        slug: 'pradha-varnya-lepa',
        category: 'Cosmetics',
        image: '/images/p6.jpg', // 679px × 829px
        price: 50,
        countInStock: 2,
        brand: 'Panchtatva',
        rating: 4.7,
        numReviews: 50,
        description: 'A revitalising facial masque specially designed for men’s skin. This is formulated with a blend of Moringa Seed Oil and Manjishtha Root Extract to firm the skin, minimise pores and visibly reduce pigmentation. Enriched with Varnya herbs, this masque clarifies the skin and enhances the complexion.',
      },
      {
        // _id: '1',
        name: 'Triphala Plus Organic',
        slug: 'triphala-plus-organic',
        category: 'Nutrition',
        image: '/images/p7.jpg', // 679px × 829px
        price: 30,
        countInStock: 7,
        brand: 'Panchtatva',
        rating: 4.9,
        numReviews: 10,
        description: 'It is a health & supplement product for boosting energy',
      },
      {
        // _id: '1',
        name: 'Divya Ras Raj Ras 1 g ',
        slug: 'divya-raj-ras',
        category: 'Medicine',
        image: '/images/p8.jpg', // 679px × 829px
        price: 35,
        countInStock: 17,
        brand: 'Panchtatva',
        rating: 4.2,
        numReviews: 110,
        description: 'It is a health product cough syrup which helps us to enhance our energy and it is like a  supplemnt product',
      },
      {
        // _id: '1',
        name: 'Aamvatari Ras 20 g',
        slug: 'aamvatari-ras',
        category: 'Medicine',
        image: '/images/p9.jpg', // 679px × 829px
        price: 42,
        countInStock: 117,
        brand: 'Panchtatva',
        rating: 4.9,
        numReviews: 1100,
        description: 'Amvatari Ras treats rheumatoid arthritis and osteoarthritis. Our dietary habits and urban, sedentary lifestyle often makes us vulnerable to toxin accumulation in body, pain in joints, etc. The herbs in Amvatari Ras are anti-inflammatory and are enriched in natural calcium. Amvatari Ras therefore fortifies your bone structure, reduces inflammation, soothes joint pain, improves flexibility and flushes out toxins from the system. Bid adieu to sore joints and regain agility with Amvatari Ras. Experience long-enduring cure with Amvatari Ras.',
      },
      {
        // _id: '1',
        name: 'Haldi Varnya Lepa',
        slug: 'haldi-varnya-lepa',
        category: 'Cosmetics',
        image: '/images/p10.jpg', // 679px × 829px
        price: 50,
        countInStock: 300,
        brand: 'Panchtatva',
        rating: 4.1,
        numReviews: 1200,
        description: 'The Forest Essentials Haldi Varnya Lepa is a moisture-replenishing facial masque infused with four varieties of Turmeric that brighten and deeply hydrate the skin. Formulated as per ancient Ayurvedic texts of the Charak Samhita, this Lepa is also blended with 10 Varnya herbs and pure steam-distilled Rosewater that deeply cleanse the skin and leave it fresh and glowing.',
      },
      {
        // _id: '1',
        name: 'Organic Haritaki Churna',
        slug: 'organic-haritaki-churna',
        category: 'Nutrition',
        image: '/images/p11.jpg', // 679px × 829px
        price: 60,
        countInStock: 350,
        brand: 'Panchtatva',
        rating: 4.5,
        numReviews: 1550,
        description: 'Haritaki - Terminalia Chebula - is an evergreen with white flowers and small yellow to orange-brown stone fruits that are used in the Ayurvedic diet. The powder tastes tart, sweet, sour, bitter and herbal all at once.',
      },
      {
        // _id: '1',
        name: 'Divya Abhyaristh',
        slug: 'divya-abyaristh',
        category: 'Medicine',
        image: '/images/p12.jpg', // 679px × 829px
        price: 350,
        countInStock: 300,
        brand: 'Panchtatva',
        rating: 4.2,
        numReviews: 150,
        description: 'Abhyaristh is a clinically proven Ayurvedic formulation that boosts your digestive system and eliminates toxins from your body. It is prepared from natural extracts that have laxative properties and induce peristaltic movements thus making evacuation of bowels pain-free. It improves digestion, increases appetite, reduces gas formation and soothes inflammation in piles. Donot let constipation and piles hold you back from enjoying life. Take Abhyaristh to experience the soothing touch of Ayurvedic cure on your stomach. '
      },
      {
        // _id: '1',
        name: 'Neem Varnya Lepa',
        slug: 'neem-varnya-lepa',
        category: 'Cosmetics',
        image: '/images/p13.jpg', // 679px × 829px
        price: 350,
        countInStock: 300,
        brand: 'Panchtatva',
        rating: 4.2,
        numReviews: 150,
        description: 'The Forest Essentials Neem Varnya Lepa is a clarifying facial masque prepared with a unique blend of herbs including Neem, Clove, Manjistha, and Shalmali that effectively helps in preventing pimples, pigmentation, and future breakouts. This is specially designed for acne-prone skin to unclog pores, deeply cleanse the skin, control sebum production, and provide continuous improvement of acne and blemishes. Set aside just 10 minutes and transform your skin!',
      },
    ],
  };
  export default data;
  